// Generated by IcedCoffeeScript 108.0.11
(function() {
  var Score, firstName, fullName, lastName, m_Score;

  firstName = "Hubert";

  lastName = "Stärk";

  m_Score = true;

  fullName = function(first, last) {
    return first + last;
  };

  Score = function() {
    return m_Score;
  };

}).call(this);
